version: Build {build}
branches:
  only:
  - master
  - dev
  - publish-test
skip_branch_with_pr: true
image: Visual Studio 2015
environment:
  clientSecret:
    secure: ExhH7vUl1alvsJas13hQH7zmirkSxuIHkPoBp0QGocTNMyVRIO9H5JhrlMa+r/EwKuDs0mauF+OJSWAPEVDBth/6jyas3A1tewdb/fQh/4o=
build_script:
- ps: .\Build\Build.ps1
artifacts:
- path: '\Build\AppxPackages'
  name: AppxPackages
- path: '\Publish\SubmissionPackage'
  name: SubmissionPackage
deploy_script:
- ps: >-
    if ($env:APPVEYOR_REPO_BRANCH -eq "publish-test")
    {
        .\Publish\InstallStoreBroker.ps1
        .\Publish\AppVeyorInit.ps1
        .\Publish\PublishToStore.ps1
    }
